import { useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { addItem } from './CartSlice.jsx'
import CartItem from './CartItem.jsx'

const image = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=700&q=85`
const categories = [
  { name:'Air Purifying', note:'Fresh energy for every room', plants:[['snake-plant','Snake Plant','A sculptural classic that thrives on neglect.','$24','photo-1593482892290-f54927ae2b2b'],['peace-lily','Peace Lily','Elegant blooms and naturally filtered air.','$28','photo-1593691509543-c55fb32e5cee'],['rubber-tree','Rubber Tree','Glossy, bold leaves for a bright corner.','$32','photo-1604762524889-3e2fcc145683'],['spider-plant','Spider Plant','A cheerful cascade of easy-going green.','$18','photo-1572688484438-313a6e50c333'],['zz-plant','ZZ Plant','Shiny foliage with serious staying power.','$26','photo-1597055181300-9a047f2f2e11'],['pothos','Golden Pothos','Fast-growing vines with a warm glow.','$20','photo-1614594975525-e45190c55d0b']] },
  { name:'Aromatic', note:'Small rituals, beautifully scented', plants:[['lavender','Lavender','Soft purple blooms with a soothing fragrance.','$22','photo-1611909023032-2d6b3134ecba'],['rosemary','Rosemary','A kitchen companion with a woodsy aroma.','$16','photo-1596547609652-9cf5d8d106c1'],['mint','Spearmint','Bright, refreshing leaves for sunny windowsills.','$14','photo-1623127303733-9e1e9c8f9296'],['eucalyptus','Eucalyptus','Silver-green stems with a clean, spa-like scent.','$25','photo-1610557892470-ae7e42f79f4f'],['jasmine','Star Jasmine','Delicate white flowers and a sweet perfume.','$30','photo-1597848212624-e19e2e6f1d6c'],['basil','Sweet Basil','Lush and fragrant, made for your kitchen.','$15','photo-1618375569909-3c8616cf7733']] },
  { name:'Low Light', note:'Beautiful, even in the shade', plants:[['calathea','Calathea Orbifolia','Striped leaves that bring quiet drama.','$34','photo-1593691509543-c55fb32e5cee'],['cast-iron','Cast Iron Plant','Dependable deep green for dim spaces.','$27','photo-1598880940080-ff9a29891b85'],['fern','Boston Fern','A feathery cloud of timeless green.','$21','photo-1614594576655-2b4ca2a5e4e8'],['chinese-evergreen','Chinese Evergreen','Patterned leaves and effortless charm.','$29','photo-1597055181300-9a047f2f2e11'],['parlor-palm','Parlor Palm','A graceful palm for softer light.','$31','photo-1597055181300-9a047f2f2e11'],['heartleaf','Heartleaf Philodendron','Velvety vines that love to wander.','$23','photo-1614594576655-2b4ca2a5e4e8']] },
]
const toPlant = ([id,name,description,cost,imageId]) => ({ id,name,description,cost,image:image(imageId) })

function ProductList({ onBackHome }) {
  const [view,setView] = useState('plants'); const [category,setCategory] = useState('All plants'); const dispatch = useDispatch(); const items = useSelector((state) => state.cart.items); const count = items.reduce((total,item) => total + item.quantity,0); const added = new Set(items.map((item) => item.id)); const shown = category === 'All plants' ? categories : categories.filter((group) => group.name === category)
  return <div className="shop-shell"><header className="navbar"><button className="brand" onClick={onBackHome}><span className="brand-mark">✳</span> paradise nursery</button><nav><button className={view === 'home' ? 'active' : ''} onClick={onBackHome}>Home</button><button className={view === 'plants' ? 'active' : ''} onClick={() => setView('plants')}>Plants</button></nav><button className="cart-button" onClick={() => setView('cart')} aria-label={`Cart with ${count} items`}><span>bag</span><b>{count}</b></button></header>{view === 'cart' ? <CartItem onContinue={() => setView('plants')} /> : <main className="catalog"><div className="catalog-heading"><div><p className="eyebrow">The collection</p><h1>Find your <em>green.</em></h1></div><p className="catalog-intro">Plants chosen to make your space feel more alive, one leaf at a time.</p></div><div className="category-tabs">{['All plants',...categories.map((group) => group.name)].map((tab) => <button key={tab} className={category === tab ? 'selected' : ''} onClick={() => setCategory(tab)}>{tab}</button>)}</div>{shown.map((group) => <section className="category-section" key={group.name}><div className="category-title"><div><h2>{group.name}</h2><p>{group.note}</p></div><span>06 varieties</span></div><div className="plant-grid">{group.plants.map((raw) => { const plant = toPlant(raw); return <article className="plant-card" key={plant.id}><div className="plant-image"><img src={plant.image} alt={plant.name} /><span className="plant-tag">{group.name}</span></div><div className="plant-info"><div><h3>{plant.name}</h3><p>{plant.description}</p></div><strong>{plant.cost}</strong></div><button className={`add-button ${added.has(plant.id) ? 'added' : ''}`} disabled={added.has(plant.id)} onClick={() => dispatch(addItem(plant))}>{added.has(plant.id) ? 'Added to Cart' : 'Add to Cart'} <span>+</span></button></article> })}</div></section>)}</main>}</div>
}
export default ProductList